name: Push to nuget feed on release

on:
  release:
    types: [published]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1

    - name: Setup MSBuild # Needed by Build NativeHelper
      uses: microsoft/setup-msbuild@v1
      
    - name: Build NativeHelper # Need to build this separately first because nuget pack doesn't seem to handle vcxproj
      working-directory: ./src/Helper
      run: |
        msbuild Helper.vcxproj /p:Configuration=Release /p:Platform=x64
    
    - name: Nuget pack
      working-directory: ./src
      run: |
        nuget restore
        gci -Recurse -Filter *.nuspec | foreach { nuget pack "$($_.DirectoryName)\$($_.BaseName).csproj" -build -properties Configuration=Release }
        
    - name: Nuget push
      working-directory: ./src
      env:
        NUGET_URL: https://pkgs.dev.azure.com/IllusionMods/Nuget/_packaging/IllusionMods/nuget/v3/index.json
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      run: |
        nuget sources update -name "IllusionMods" -username "token" -password ${env:NUGET_TOKEN}
        nuget push *.nupkg -apikey key -noninteractive -skipduplicate -src ${env:NUGET_URL}
